export const CONFIG_PATH = "./config.json";

export const SERVER_EVENT_TYPES = {
  ABORT: "ABORT",
  CLOSE: "CLOSE",
  PONG: "PONG",
};

export const REQUEST_TYPES = {
  CONNECT: "CONNECT",
  DISCONNECT: "DISCONNECT",
  INVENTORY: "INVENTORY",
  FETCH_CHARACTER: "FETCH_CHARACTER",
  PING: "CLIENT_PING_TIME",
};

export const RESPONSE_TYPES = {
  CHARACTER: "CHARACTER",
  AREA: "AREA",
  INPUT: "INPUT",
  AVAILABLE_CHARACTERS: "AVAILABLE_CHARACTERS",
  CHAT: "CHAT",
  SERVER_PING_TIME: "SERVE_PING_TIME",
  SERVER_ACK_PING_TIME: "SERVER_ACK_PING_TIME",
};

export const ACTION_TYPES = {
  CHARACTER: "CHARACTER",
};
