namespace GameProtocol;

table Player {
  id: int;
  firstName: string;
  lastName: string;
  email: string;
}

table Zone {
  id: string;
  areaId: string;
  mapName: string;
}

struct Position {
  x: float;
  y: float;
}

table Stats {
  hp: int;
  max_hp: int;
  mana: int;
  max_mana: int;
  speed: int;
}

table Character {
  id: int;
  player: Player;
  name: string;
  level: int;
  position: Position;
  stats: Stats;
  zone: Zone;
  is_alive: bool;
}

root_type Character;