export const REQUEST_TYPES = {
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  JOIN: 'JOIN',
  LEAVE: 'LEAVE',
  PING: 'CLIENT_PING_TIME',
  COMMAND: 'COMMAND'
}

export const RESPONSE_TYPES = {
  JOIN: 'JOIN',
  AVAILABLE_CHARACTERS: 'AVAILABLE_CHARACTERS',
  CHAT: 'CHAT',
  SERVER_PING_TIME: 'SERVE_PING_TIME',
  SERVER_ACK_PING_TIME: 'SERVER_ACK_PING_TIME'
}