export const SERVER_EVENT_TYPES = {
  ABORT: 'ABORT',
  CLOSE: 'CLOSE',
  PONG: 'PONG'
}

export const REQUEST_TYPES = {
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  JOIN: 'JOIN',
  LEAVE: 'LEAVE',
  ACTION: 'ACTION',
  PING: 'CLIENT_PING_TIME',
  COMMAND: 'COMMAND'
}

export const RESPONSE_TYPES = {
  AVAILABLE_CHARACTERS: 'AVAILABLE_CHARACTERS',
  CHAT: 'CHAT',
  SERVER_PING_TIME: 'SERVE_PING_TIME',
  SERVER_ACK_PING_TIME: 'SERVER_ACK_PING_TIME'
}

export const ACTION_TYPES = {
  CHARACTER: 'CHARACTER'
}